# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Oh-my-zsh theme
ZSH_THEME="mytheme"

plugins=(git macos composer docker docker-compose colorize)

# User configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export LANG=en_US.UTF-8

source $ZSH/oh-my-zsh.sh

# use .localrc for SUPER SECRET stuff that you don't want in your public, versioned repo.
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# Load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc

export GOPATH=$HOME/dev/go
export PATH=$HOME/dev/go/bin:$PATH
export PATH="/Users/shaunegan/pear/share/pear:$PATH"
export PATH="/Users/shaunegan/pear/bin:$PATH"
export PATH="/usr/local/opt/php@7.3/bin:$PATH"
export PATH="/usr/local/opt/php@7.3/sbin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/shaunegan/bin/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/shaunegan/bin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/shaunegan/bin/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/shaunegan/bin/google-cloud-sdk/completion.zsh.inc'; fi

export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

eval "$(/opt/homebrew/bin/brew shellenv)"
