# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh
# export DOT_FILES=~/.dotfiles

# Oh-my-zsh theme
ZSH_THEME="mytheme"

plugins=(git, osx, composer, docker, docker-compose, colorize)

# User configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export LANG=en_US.UTF-8

source $ZSH/oh-my-zsh.sh

# use .localrc for SUPER SECRET stuff that you don't want in your public, versioned repo.
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# All of our zsh files
# typeset -U config_files
# config_files=($DOT_FILES/**/*.zsh)

# Load the path files
# for file in ${(M)config_files:#*/path.zsh}
# do
#   source $file
# done

# load the rest
# for file in ${${config_files:#*/path.zsh}}
# do
#  source $file
# done
#
# unset config_files

# Load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/shaun/dev/iflix/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/shaun/dev/iflix/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/shaun/dev/iflix/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/shaun/dev/iflix/node_modules/tabtab/.completions/sls.zsh
